import {
  volumeTiers,
  assetRows,
  pricingPolicy,
} from '../content/pricing/pricingTables'
import { pageUpdatedAt } from '../content/pageUpdatedAt'

const siteUrl = 'https://hodle.com.br'

/**
 * Renders the pricing page as markdown. The tables come from the same module
 * `/precos` renders, so the published numbers can never diverge.
 */
export const pricingToMarkdown = (): string =>
  [
    '# Preços e taxas',
    '',
    `> ${pricingPolicy.description}`,
    '',
    `Fonte canônica: ${siteUrl}/precos — atualizado em ${pageUpdatedAt.precos}.`,
    '',
    'Esta página reúne a tabela comercial e orienta como conferir o preço de cada operação. API, Lightning e wallet podem ter regras próprias. Confira o fluxo habilitado, a condição contratada e a cotação antes de confirmar. Se a cotação divergir do contrato, esclareça a diferença com a Hodle antes de executar.',
    '',
    '## Tabela comercial por volume: on-ramp e off-ramp',
    '',
    pricingPolicy.volumeScope,
    '',
    '| Volume mensal | Taxa de serviço |',
    '| --- | --- |',
    ...volumeTiers.map((tier) => `| ${tier.volume} | ${tier.fee} |`),
    '',
    'Quando sua condição comercial adota esta tabela:',
    '',
    '- Volume é a soma, em reais, das operações abrangidas pela condição comercial, nas duas direções, pelo valor bruto liquidado no mês. Operações em Bitcoin incluídas no contrato entram pelo valor em reais da liquidação.',
    '- A faixa vale para o mês inteiro e é definida pelo volume do mês fechado anterior. Sua aplicação depende de a conta e o fluxo estarem enquadrados nessa condição comercial.',
    '- A taxa da faixa é aplicada sobre todo o volume do mês, não em fatias.',
    '- Em cada operação abrangida pela tabela, a taxa é o maior valor entre o percentual da faixa e R$ 0,75. Esse mínimo não define a tarifa de API, Lightning ou wallet.',
    '',
    '## Como calcular a taxa de serviço',
    '',
    'Exemplos ilustrativos para operações abrangidas pela tabela comercial, não cotações: na faixa de 2%, uma operação de R$ 1.000 tem R$ 20 de taxa de serviço. Em uma operação de R$ 20, o percentual seria R$ 0,40, mas o mínimo da tabela leva a taxa a R$ 0,75. O mínimo substitui o resultado menor; não é somado a ele. Esses exemplos não afirmam que qualquer fluxo aceite os tickets usados.',
    '',
    'A taxa de serviço isolada não informa quanto USDT ou USDC será entregue ou debitado. Confira a cotação e o resultado da operação. Pela API, /api/quote é uma simulação indicativa, sem reserva de câmbio. O payout possui uma cotação própria, vinculada ao beneficiário, cujo quoteId pode ser usado na execução. Verifique se a condição aplicada à sua conta corresponde ao contrato antes de confirmar. Consulte a [referência de cotação](https://docs.hodle.com.br/docs/quote) e a [confirmação de beneficiário do payout](https://docs.hodle.com.br/docs/wallet-payout-beneficiary).',
    '',
    '## Condição negociada',
    '',
    'A tabela acima é uma referência comercial. A proposta e o contrato definem quais fluxos, ativos e condições se aplicam à sua integração. A documentação de um endpoint pode descrever uma tarifa própria; confirme sua aplicação à conta e compare com o contrato e com o valor apresentado na operação.',
    '',
    '## Payout por API e Lightning para Pix',
    '',
    pricingPolicy.payout,
    '',
    'Consulte a [documentação de taxas do payout](https://docs.hodle.com.br/docs/wallet-payout#fees).',
    '',
    pricingPolicy.lightning,
    '',
    `Consulte a [documentação de taxas da invoice Lightning](https://docs.hodle.com.br/docs/lightning-invoice#fees). Referências revisadas em ${pageUpdatedAt.precos}.`,
    '',
    '## Ativos e redes',
    '',
    'O catálogo abaixo não determina a tarifa de cada combinação. Ativo, rede, operação e condição da conta podem alterar a precificação. BRLA e BRS têm fluxos próprios; a referência comercial de Pix para Real on-chain está descrita adiante.',
    '',
    '| Ativo | Redes |',
    '| --- | --- |',
    ...assetRows.map((row) => `| ${row.asset} | ${row.networks} |`),
    '',
    'Esta é a abrangência do catálogo, não uma matriz de suporte de cada endpoint. Uma rede disponível para compra ou transferência pode não estar disponível para payout. Confira o ativo, a rede e a operação na documentação e nas opções habilitadas para a sua conta.',
    '',
    '## Transferência entre carteiras',
    '',
    'Mover saldo de uma carteira da Hodle para outra carteira da Hodle, dentro da mesma rede, é sem custo. Vale nas redes Polygon, Base e Solana. Isso não é a mesma coisa que transferência entre redes: sair de uma rede e chegar em outra envolve ponte ou conversão, tem custo real e não tem preço publicado.',
    '',
    '## Pix para Real on-chain',
    '',
    'Receber um Pix e liquidá-lo em Real tokenizado on-chain não envolve conversão cambial, e por isso não é cobrado em percentual: R$ 0,75 por transação em tickets de até R$ 5.000. Em tickets acima de R$ 5.000, a tarifa passa a ser 0,10% do valor da transação no lugar dos R$ 0,75 — os dois não se somam — e a tarifa total de uma transação nunca passa de R$ 50,00. O Real tokenizado é entregue como BRLA na rede Polygon ou como BRS na rede Solana. Esse rail é contratado, não self-serve.',
    '',
    '## Contas PJ nominais',
    '',
    'Clientes que precisam emitir contas PJ nominais em nome próprio pagam um valor único de implantação de R$ 15.000. O valor cobre a habilitação do recurso, e não há custo por conta criada depois disso. Não existe taxa de setup para usar o on-ramp, o off-ramp ou o Pix para Real on-chain.',
    '',
    '## Contestações',
    '',
    'Cada contestação de Pix aberta pelo pagador — o MED, mecanismo especial de devolução do Banco Central — custa R$ 10,00 por ocorrência tratada, independentemente do resultado da análise.',
    '',
    '## O que está incluído',
    '',
    'Nas combinações de ativo e rede suportadas pelos endpoints de transferência e payout em Polygon, Base e Solana, a taxa de rede é patrocinada pela Hodle. O cliente não precisa manter a moeda nativa dessas redes apenas para pagar essa taxa. Esse benefício não elimina a taxa de serviço nem amplia a cobertura de redes do endpoint. Confira as combinações aceitas nas referências de [transferência](https://docs.hodle.com.br/docs/wallet-transfer) e [payout](https://docs.hodle.com.br/docs/wallet-payout). A disponibilidade continua sujeita às permissões da conta.',
    '',
    '## O que não está nesta página',
    '',
    'Duas categorias de taxa não são publicadas porque dependem do par de redes e do modelo de negócio do cliente:',
    '',
    '- Taxas de transferência entre redes.',
    '- Taxas de conversão entre ativos.',
    '',
    'Para esses casos o canal correto é o time comercial. Qualquer valor citado para essas duas categorias fora desse canal não é oficial.',
    '',
    '## Como comparar preços',
    '',
    'Ao comparar preços, identifique a operação, a conta e a condição aplicável. As faixas por volume e seu mínimo valem para operações abrangidas por essa tabela comercial; não são a tarifa universal de API, Lightning ou wallet. Use a documentação específica e a cotação da operação para conferir taxa e total. A gratuidade de transferência entre carteiras Hodle na mesma rede não se estende a transferências entre redes. O preço de Pix para Real on-chain depende da faixa de ticket descrita nesta página.',
    '',
  ].join('\n')
